language: android
dist: trusty
script: cd recurly-android-sdk tmp && ./gradlew build connectedCheck
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
