language: android
dist: trusty
script: cd recurly-android-sdk tmp && ./gradlew build connectedCheck
android:
  components:
    - build-tools-21.1.1
    - android-21
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
